add_newline = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "🌿 "
style = "bold green"

[cmd_duration]
min_time = 2_000
style = "bold yellow"
